//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Articul { get; set; }
        public string Colour { get; set; }
        public string Size { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
