//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> NumberOfItems { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public string Details { get; set; }
    }
}
