//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Articul { get; set; }
        public string Image { get; set; }
        public Nullable<int> MinQuantity { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SubSectionID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> RatingCount { get; set; }
        public Nullable<int> OrderCount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string About { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
    }
}
